name: Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: Is release? (Will create tag and update version)
        required: true
        default: false
        type: boolean
      release-version:
        description: Released version (x.y.z)
        required: true
        type: string
      next-version:
        description: Next version (x.y.z)
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.java.installations.auto-detect=false -Dorg.gradle.warning.mode=fail'

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  ci-low-cadence:
    uses: ./.github/workflows/ci-low-cadence.yml

  codeql:
    uses: ./.github/workflows/codeql.yml

  pre-release:
    name: Update version, tag repo, and return sha
    permissions:
      contents: write
    needs: [ ci, ci-low-cadence, codeql ]
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        if: ${{ inputs.release }}
        name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - id: validate
        if: ${{ inputs.release }}
        name: Validate no new commits
        run: |
          if test $(git rev-parse HEAD) != '${{ github.sha }}'
          then exit 1
          fi
      - id: tag-version
        if: ${{ inputs.release }}
        name: Update version, tag repo, and return current SHA
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@aeron.io"
          echo ${{ inputs.release-version }} > version.txt
          git add version.txt
          git commit -m "${{ inputs.release-version }} version update."
          git push
          git tag ${{ inputs.release-version }}
          git push origin refs/tags/${{ inputs.release-version }}

  release:
    name: Release java artifacts
    permissions:
      contents: read
      packages: write
    needs: pre-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.release && inputs.release-version || github.sha }}
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 8
      - name: Setup BUILD_JAVA_HOME & BUILD_JAVA_VERSION
        run: |
          java -Xinternalversion
          echo "BUILD_JAVA_HOME=${JAVA_HOME}" >> $GITHUB_ENV
          echo "BUILD_JAVA_VERSION=8" >> $GITHUB_ENV
      - name: Publish a release
        run: ./gradlew publish
        env:
          SIGNING_GPG_SECRET_KEY: ${{ secrets.signingKey }}
          SIGNING_GPG_PASSWORD: ${{ secrets.signingPassword }}
          OSSRH_USERNAME: ${{ secrets.ossrhUsername }}
          OSSRH_PASSWORD: ${{ secrets.ossrhPassword }}

  github-release:
    if: ${{ inputs.release }}
    name: Create Github Release after release
    permissions:
      contents: write
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.release-version }}
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.release-version }}
          release_name: Release ${{ inputs.release-version }}
          draft: true

  post-release:
    if: ${{ inputs.release }}
    name: Update version after release
    permissions:
      contents: write
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Commit snapshot version to current branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@aeron.io"
          echo ${{ inputs.next-version }}-SNAPSHOT > version.txt
          git add version.txt
          git status
          git commit -m "${{ inputs.next-version }}-SNAPSHOT version update."
          git push